#!/bin/bash

#rm library/liblibrary.a 
#rm libraryTest/libraryTest 
pushd library
if [[ ! -e "Makefile" ]]; then
  cmake .
fi
make
popd
pushd libraryTest
if [[ ! -e "Makefile" ]]; then
  cmake .
fi
make
./libraryTest "$@"
popd
